import { Metadata } from 'next';

import ReduxProvider from '@providers/redux';

import '@styles/globals.css';
import StyledComponentsProvider from '@providers/styledComponent';

export const metadata: Metadata = {
  title: 'snapFood',
  description: 'Generated by Mohsen Kermanifa',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='fr'>
      <body >
        <StyledComponentsProvider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </StyledComponentsProvider>
      </body>
    </html>
  );
}
